"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";

const storageKey = "rb-nepali-translation-cache-v2";
type Cache = Record<string, string>;
const preferredTranslations: Cache = {
  "R.B. Complex": "आर.बी. कम्प्लेक्स",
  "R.B. Complex.": "आर.बी. कम्प्लेक्स।",
  "R.B.": "आर.बी.",
  "R.B. Complex · New Road": "आर.बी. कम्प्लेक्स · न्यू रोड",
  "Everything you love.": "तपाईंलाई मन पर्ने सबै कुरा।",
  "Under one roof.": "एकै छानामुनि।",
  "Shop fashion, footwear, electronics, accessories and everyday services in the heart of Kathmandu's New Road district.": "काठमाडौंको न्यू रोडको मुटुमा फेसन, जुत्ता, इलेक्ट्रोनिक्स, सामान र दैनिक सेवाहरू एकै ठाउँमा पाउनुहोस्।",
  "Discover R.B.": "आर.बी. कम्प्लेक्स पत्ता लगाउनुहोस्",
  "Shopping made": "किनमेललाई",
  "easy to explore.": "सजिलो बनाउनुहोस्।",
  "More reasons": "आउनका थप",
  "to stop by.": "कारणहरु।",
  "What's new at R.B.": "आर.बी. कम्प्लेक्समा नयाँ के छ?",
  "Come to New Road": "न्यू रोड आउनुहोस्",
  "Explore stores": "पसलहरू हेर्नुहोस्",
  "What's happening": "के हुँदैछ हेर्नुहोस्",
  "Welcome to": "स्वागत छ",
  "Complex": "कम्प्लेक्स",
  "Fashion": "फेसन",
  "Footwear": "जुत्ता",
  "Electronics": "इलेक्ट्रोनिक्स",
  "Offers": "अफरहरू",
  "Visit": "भ्रमण",
  "Explore your next find, discover seasonal inspiration, and plan a day in the heart of New Road.": "न्यू रोडको मुटुमा आफ्नो रोजाइका सामान खोज्नुहोस्, मौसमी नयाँपन पत्ता लगाउनुहोस् र किनमेलको दिन योजना बनाउनुहोस्।",
  "Shop": "किनमेल",
  "Browse the store directory": "पसल सूची हेर्नुहोस्",
  "See what's on sale": "हालका अफरहरू हेर्नुहोस्",
  "What's On": "के हुँदैछ",
  "Events & experiences": "कार्यक्रम र अनुभवहरू",
  "Featured now": "अहिलेका विशेष आकर्षण",
  "A little inspiration for your next shopping day. Explore our sample seasonal highlights below.": "तपाईंको अर्को किनमेल यात्राका लागि केही प्रेरणा। तलका मौसमी विशेषताहरू हेर्नुहोस्।",
  "Seasonal campaign": "मौसमी अभियान",
  "New season.": "नयाँ मौसम।",
  "New finds.": "नयाँ रोजाइहरू।",
  "Discover fresh arrivals across fashion, footwear and accessories.": "फेसन, जुत्ता र एक्सेसरिजका नयाँ आगमनहरू पत्ता लगाउनुहोस्।",
  "Weekend": "सप्ताहन्त",
  "Shop & save": "किनमेल गर्नुहोस्, बचत गर्नुहोस्",
  "Prototype offer space for participating stores.": "सहभागी पसलहरूका अफरका लागि नमुना स्थान।",
  "Discover": "पत्ता लगाउनुहोस्",
  "Highlight recently opened stores and services.": "हालै खुलेका पसल र सेवाहरूका बारेमा जान्नुहोस्।",
  "Shop by category": "तल्लाअनुसार किनमेल",
  "Whatever brings you in.": "तपाईंको रोजाइअनुसार।",
  "From a new look to everyday essentials, find a place to start exploring.": "नयाँ पहिरनदेखि दैनिक आवश्यकतासम्म, आफ्नो किनमेलको सुरुवात यहीँबाट गर्नुहोस्।",
  "Wear it your way.": "आफ्नै शैलीमा लगाउनुहोस्।",
  "Explore clothing & style →": "पोशाक र शैली हेर्नुहोस् →",
  "Step into something new.": "नयाँ रोजाइतर्फ पाइला चाल्नुहोस्।",
  "Explore shoes & accessories →": "जुत्ता र एक्सेसरिज हेर्नुहोस् →",
  "Beauty & accessories": "सौन्दर्य र एक्सेसरिज",
  "The finishing touch.": "तपाईंको शैलीको अन्तिम स्पर्श।",
  "Explore personal style →": "व्यक्तिगत शैली हेर्नुहोस् →",
  "Electronics & services": "इलेक्ट्रोनिक्स र सेवाहरू",
  "Everyday essentials.": "दैनिक आवश्यकताहरू।",
  "Explore technology & services →": "प्रविधि र सेवाहरू हेर्नुहोस् →",
  "Accessories": "एक्सेसरिज",
  "Services": "सेवाहरू",
  "New Road": "न्यू रोड",
  "A full day at R.B.": "आर.बी. कम्प्लेक्समा पूरा दिन",
  "Shop. Meet.": "किनमेल गर्नुहोस्। भेटघाट गर्नुहोस्।",
  "Discover.": "नयाँ कुरा पत्ता लगाउनुहोस्।",
  "Make room for a little discovery. Browse the shops, meet a friend, and enjoy the energy of New Road.": "नयाँ कुरा खोज्न समय निकाल्नुहोस्। पसलहरू हेर्नुहोस्, साथीभाइसँग भेट्नुहोस् र न्यू रोडको रौनक अनुभव गर्नुहोस्।",
  "Style": "शैली",
  "Start with something new.": "केही नयाँबाट सुरु गर्नुहोस्।",
  "Fresh fashion, accessories and everyday finds across multiple floors.": "विभिन्न तल्लामा नयाँ फेसन, एक्सेसरिज र दैनिक उपयोगका सामानहरू पाउनुहोस्।",
  "Meet": "भेटघाट",
  "Make time for people.": "आफ्ना मानिसका लागि समय निकाल्नुहोस्।",
  "Catch up with friends and explore nearby food spots after a day of shopping.": "किनमेलपछि साथीभाइसँग भेट्नुहोस् र वरपरका खानाका ठाउँहरू घुम्नुहोस्।",
  "Explore": "अन्वेषण",
  "See what's around the corner.": "वरिपरिका नयाँ कुरा हेर्नुहोस्।",
  "New stores, seasonal campaigns and changing retail moments.": "नयाँ पसल, मौसमी अभियान र बदलिँदो किनमेल अनुभव।",
  "Your day, your pace": "तपाईंको दिन, तपाईंको गति",
  "From first stop to last bag.": "पहिलो रोजाइदेखि अन्तिम झोलासम्म।",
  "Take your time, explore something different, and make the most of your day in Kathmandu.": "आफ्नो समय लिएर फरक कुरा खोज्नुहोस् र काठमाडौंको दिनलाई भरपूर बनाउनुहोस्।",
  "Arrive in New Road": "न्यू रोड आइपुग्नुहोस्",
  "Plan the stores you want before you step inside.": "भित्र पस्नुअघि जान चाहेका पसलहरूको योजना बनाउनुहोस्।",
  "Browse & compare": "हेर्नुहोस् र तुलना गर्नुहोस्",
  "Move between fashion, footwear, electronics and services.": "फेसन, जुत्ता, इलेक्ट्रोनिक्स र सेवाहरूबीच आफ्नो रोजाइ खोज्नुहोस्।",
  "Catch what's new": "नयाँ कुरा हेर्नुहोस्",
  "Check seasonal campaigns, offers and new openings.": "मौसमी अभियान, अफर र नयाँ पसलहरूबारे जानकारी लिनुहोस्।",
  "One last stop": "अन्तिम रोजाइ",
  "Save a favourite store or plan your next visit.": "मनपरेको पसल सम्झनुहोस् वा अर्को भ्रमणको योजना बनाउनुहोस्।",
  "Find your way": "आफ्नो बाटो पत्ता लगाउनुहोस्",
  "Know the floor": "तल्ला बुझ्नुहोस्",
  "before you arrive.": "आउनुअघि नै।",
  "Explore the sample directory and get an idea of how to plan your shopping stops.": "नमुना पसल सूची हेरेर आफ्नो किनमेलको योजना कसरी बनाउने भन्ने बुझ्नुहोस्।",
  "Four levels.": "चार तल्ला।",
  "One clear guide.": "एउटै स्पष्ट मार्गदर्शन।",
  "Prototype floor numbers are shown for visual direction. The final site can use verified plans and real tenant locations.": "दृश्य मार्गदर्शनका लागि नमुना तल्ला नम्बर देखाइएका छन्। अन्तिम वेबसाइटमा प्रमाणित नक्सा र वास्तविक पसल स्थान समावेश गरिनेछन्।",
  "Browse stores": "पसलहरू हेर्नुहोस्",
  "Plan your visit": "भ्रमण योजना बनाउनुहोस्",
  "Prototype design principle": "नमुना डिजाइन सिद्धान्त",
  "Seen at R.B.": "आर.बी. कम्प्लेक्समा देखिएका",
  "Retail in motion.": "चलायमान किनमेल अनुभव।",
  "A little shopping inspiration. Gallery photographs are illustrative concept images.": "किनमेलका लागि केही प्रेरणा। ग्यालरीका तस्बिरहरू उदाहरणका लागि प्रयोग गरिएका अवधारणा तस्बिर हुन्।",
  "Make R.B. part of": "आर.बी. कम्प्लेक्सलाई बनाउनुहोस्",
  "your next city day.": "तपाईंको अर्को सहर भ्रमणको हिस्सा।",
  "Find your stores, check what's happening, then get directions — all from one place.": "आफ्ना पसलहरू खोज्नुहोस्, के हुँदैछ हेर्नुहोस् र दिशानिर्देश पाउनुहोस्—सबै एकै ठाउँमा।",
  "Plan your visit ↗": "भ्रमण योजना बनाउनुहोस् ↗",
  "See all stores": "सबै पसल हेर्नुहोस्",
  "About R.B. Complex": "आर.बी. कम्प्लेक्सबारे",
  "A New Road": "न्यू रोडको",
  "landmark.": "पहिचान।",
  "A lasting part of Kathmandu’s commercial life, shaped by the people, businesses and energy of New Road.": "न्यू रोडका मानिस, व्यवसाय र रौनकसँग जोडिएको काठमाडौंको व्यावसायिक जीवनको एक महत्वपूर्ण हिस्सा।",
  "Our history": "हाम्रो इतिहास",
  "A landmark in the heart": "मुटुमा रहेको एक पहिचान",
  "of New Road.": "न्यू रोडको।",
  "A Kathmandu shopping landmark since the late 1990s.": "सन् १९९० को दशकको अन्त्यदेखि काठमाडौंको परिचित किनमेल गन्तव्य।",
  "Growing with Kathmandu": "काठमाडौंसँगै अघि बढ्दै",
  "New Road’s enduring": "न्यू रोडको स्थायी",
  "business identity.": "व्यावसायिक पहिचान।",
  "Explore the complex": "कम्प्लेक्स चिन्नुहोस्",
  "See what’s here today.": "आज यहाँ के छ, हेर्नुहोस्।",
  "Plan a visit": "भ्रमण योजना बनाउनुहोस्",
  "Store directory": "पसल निर्देशिका",
  "Find your": "आफ्ना",
  "favourites.": "मनपर्ने पसल खोज्नुहोस्।",
  "Search by store, category or floor.": "पसल, श्रेणी वा तल्लाअनुसार खोज्नुहोस्।",
  "Stores": "पसलहरू",
  "Everything": "सबै कुरा",
  "in one place.": "एकै ठाउँमा।",
  "All": "सबै",
  "Ground Floor": "भुइँतल्ला",
  "First Floor": "पहिलो तल्ला",
  "Second Floor": "दोस्रो तल्ला",
  "Third Floor": "तेस्रो तल्ला",
  "Directory overview": "निर्देशिका अवलोकन",
  "Browse by": "हेर्नुहोस्",
  "floor and category.": "तल्ला र श्रेणीअनुसार।",
  "Shop by floor": "तल्लाअनुसार पसलहरू",
  "Know where to start.": "कहाँबाट सुरु गर्ने, बुझ्नुहोस्।",
  "Featured categories": "विशेष श्रेणीहरू",
  "Find the things": "तपाईंले खोजेका वस्तुहरू",
  "you came for.": "यहाँ पाउनुहोस्।",
  "Need help?": "सहयोग चाहिन्छ?",
  "Make shopping simpler.": "किनमेललाई अझ सहज बनाउनुहोस्।",
  "Next step": "अर्को चरण",
  "Found what you need?": "खोजेको कुरा भेट्नुभयो?",
  "Come find us.": "हामीलाई भेट्न आउनुहोस्।",
  "Offers & promotions": "अफर र प्रचारहरू",
  "More value.": "थप फाइदा।",
  "More reasons to shop.": "किनमेलका थप कारण।",
  "A dedicated space for seasonal campaigns and tenant promotions.": "मौसमी अभियान र सहभागी पसलका प्रचारका लागि छुट्टै स्थान।",
  "Current campaigns": "हालका अभियानहरू",
  "Offers worth": "लाभदायक अफरहरू",
  "coming in for.": "जसका लागि आउन लायक छ।",
  "More promotions": "थप प्रचारहरू",
  "Something for": "हरेक",
  "every kind of shopper.": "किनमेलकर्ताका लागि केही न केही।",
  "Campaign content strategy": "अभियान सामग्रीको योजना",
  "How offers work": "अफर कसरी काम गर्छन्",
  "Clear before": "किनमेलअघि",
  "you shop.": "स्पष्ट जानकारी।",
  "Don't miss what's new": "नयाँ कुरा नछुटाउनुहोस्",
  "Offers change.": "अफर परिवर्तन हुन्छन्।",
  "Your plans can too.": "तपाईंको योजना पनि बदलिन सक्छ।",
  "More than": "यसले दिन्छ",
  "a shopping trip.": "किनमेलभन्दा बढी अनुभव।",
  "Events, new openings, seasonal moments and reasons to return.": "कार्यक्रम, नयाँ पसल, मौसमी गतिविधि र फेरि आउनका कारणहरू।",
  "See what's": "आउँदै गरेका",
  "coming up.": "कार्यक्रम हेर्नुहोस्।",
  "Calendar": "क्यालेन्डर",
  "Plan around": "कार्यक्रमअनुसार",
  "what's happening.": "आफ्नो योजना बनाउनुहोस्।",
  "Stories from R.B.": "आर.बी. कम्प्लेक्सका कथाहरू",
  "New openings.": "नयाँ पसलहरू।",
  "Fresh reasons to return.": "फेरि आउनका नयाँ कारणहरू।",
  "Stay connected": "सम्पर्कमा रहनुहोस्",
  "What's next at R.B.": "आर.बी. कम्प्लेक्समा अब के आउँदैछ?",
  "Make a day of it": "दिनलाई विशेष बनाउनुहोस्",
  "See what's happening.": "के हुँदैछ हेर्नुहोस्।",
  "Then come by.": "त्यसपछि आउनुहोस्।",
  "Gallery": "ग्यालरी",
  "See what’s": "भित्र रहेका",
  "waiting inside.": "आकर्षणहरू हेर्नुहोस्।",
  "At R.B. Complex": "आर.बी. कम्प्लेक्समा",
  "New Road,": "न्यू रोड",
  "in focus.": "नजिकबाट।",
  "Inside R.B.": "आर.बी. कम्प्लेक्सभित्र",
  "New season style": "नयाँ मौसमको शैली",
  "Step out": "बाहिर निस्कनुहोस्",
  "Everyday tech": "दैनिक प्रविधि",
  "Small details": "साना तर महत्वपूर्ण कुरा",
  "The finishing touch": "अन्तिम स्पर्श",
  "Find something": "घर लैजान लायक",
  "worth taking home.": "केही खोज्नुहोस्।",
  "Ideas, new finds and practical guides for enjoying your time at R.B. Complex and around New Road.": "आर.बी. कम्प्लेक्स र न्यू रोडमा समय बिताउन उपयोगी सुझाव, नयाँ रोजाइ र व्यवहारिक मार्गदर्शन।",
  "Explore stories": "कथाहरू पढ्नुहोस्",
  "Latest stories": "नयाँ कथाहरू",
  "Find your next": "तपाईंको अर्को",
  "favourite thing.": "मनपर्ने कुरा खोज्नुहोस्।",
  "Read story": "कथा पढ्नुहोस्",
  "Plan your next stop": "अर्को गन्तव्य योजना बनाउनुहोस्",
  "Everything you need": "तपाईंलाई चाहिने सबै जानकारी",
  "Visitor information": "आगन्तुक जानकारी",
  "See you at": "भेटौँ",
  "Pako, New Road, Kathmandu.": "पाको, न्यू रोड, काठमाडौं।",
  "Right in the heart": "ठ्याक्कै मुटुमा",
  "Address": "ठेगाना",
  "Phone": "फोन",
  "Visitor note": "आगन्तुक सूचना",
  "Open Google Maps ↗": "गुगल म्याप खोल्नुहोस् ↗",
  "Call R.B. Complex": "आर.बी. कम्प्लेक्समा फोन गर्नुहोस्",
  "Parking": "पार्किङ",
  "Access": "पहुँच",
  "Visitor info": "आगन्तुक जानकारी",
  "Getting here": "यहाँ कसरी आउने",
  "Choose the way": "तपाईंका लागि उपयुक्त",
  "that works for you.": "बाटो छान्नुहोस्।",
  "By foot": "पैदल",
  "By vehicle": "सवारीबाट",
  "Public transport": "सार्वजनिक यातायात",
  "Plan your day": "आफ्नो दिन योजना बनाउनुहोस्",
  "A smoother visit": "झन्झटरहित भ्रमण",
  "starts online.": "अनलाइनबाट सुरु हुन्छ।",
  "Before": "अघि",
  "Arrival": "आइपुग्दा",
  "Inside": "भित्र",
  "After": "पछि",
  "Common questions": "सामान्य प्रश्नहरू",
  "Helpful before": "घरबाट निस्कनुअघि",
  "you leave home.": "उपयोगी जानकारी।",
  "Ready to go?": "जान तयार हुनुहुन्छ?",
  "New Road is waiting.": "न्यू रोड तपाईंलाई पर्खिरहेको छ।",
  "We'll see you at R.B.": "आर.बी. कम्प्लेक्समा भेटौँला।",
  "Leasing at R.B.": "आर.बी. कम्प्लेक्समा लिजिङ",
  "Bring your brand": "आफ्नो ब्रान्डलाई",
  "to New Road.": "न्यू रोडमा ल्याउनुहोस्।",
  "Make an enquiry ↓": "सोधपुछ गर्नुहोस् ↓",
  "Leasing enquiry": "लिजिङ सोधपुछ",
  "Tell us about": "आफ्नो",
  "your business.": "व्यवसायबारे बताउनुहोस्।",
  "Your name": "तपाईंको नाम",
  "Business / brand": "व्यवसाय / ब्रान्ड",
  "Category": "श्रेणी",
  "Requirements": "आवश्यकताहरू",
  "Submit prototype enquiry →": "नमुना सोधपुछ पठाउनुहोस् →",
  "Why R.B.": "किन आर.बी. कम्प्लेक्स?",
  "A New Road address": "न्यू रोडको ठेगाना",
  "with visibility.": "उत्कृष्ट पहुँचसहित।",
  "Available-space concept": "उपलब्ध स्थानको अवधारणा",
  "Show the space.": "स्थान देखाउनुहोस्।",
  "Sell the possibility.": "सम्भावना प्रस्तुत गर्नुहोस्।",
  "Leasing process": "लिजिङ प्रक्रिया",
  "From interest": "रुचिदेखि",
  "to opening day.": "उद्घाटनको दिनसम्म।",
  "Leasing FAQ": "लिजिङसम्बन्धी प्रश्नहरू",
  "Before you": "तपाईंले सोधपुछ",
  "make an enquiry.": "गर्नुअघि।",
  "Located in the heart of Kathmandu’s historic New Road,": "काठमाडौंको ऐतिहासिक न्यू रोडको मुटुमा अवस्थित",
  "Ranamukteshwor Business Complex (RB Complex)": "राणामुक्तेश्वर बिजनेस कम्प्लेक्स (आर.बी. कम्प्लेक्स)",
  "has been part of the city’s evolving commercial landscape for more than two decades.": "दुई दशकभन्दा बढी समयदेखि सहरको बदलिँदो व्यावसायिक परिदृश्यको हिस्सा रहँदै आएको छ।",
  "Recognized as the": "यसलाई",
  "first major commercial complex developed under the BOOT model in Kathmandu": "काठमाडौंमा बुट मोडेलअन्तर्गत विकसित पहिलो प्रमुख व्यावसायिक कम्प्लेक्सका रूपमा चिनिन्छ",
  ", RB Complex brought numerous businesses and products together under one roof—an important new approach to organized shopping in the city.": "। यसले धेरै व्यवसाय र उत्पादनलाई एउटै छानामुनि ल्याएर सहरको व्यवस्थित किनमेलमा नयाँ आयाम थप्यो।",
  "Late 1990s": "सन् १९९० को दशकको अन्त्य",
  "January 2001": "जनवरी २००१",
  "Today": "आज",
  "By January 2001, RB Complex was already recognized as a prominent building in Ranamukteshwor, with an architectural character that aimed to connect traditional Kathmandu and modern commerce.": "जनवरी २००१ सम्ममा आर.बी. कम्प्लेक्स राणामुक्तेश्वरको एक परिचित भवन बनिसकेको थियो। यसको वास्तुशिल्पले परम्परागत काठमाडौं र आधुनिक व्यापारबीच सम्बन्ध जोड्ने प्रयास गरेको थियो।",
  "Through changing trends and generations of businesses, the complex has remained connected to the energy of New Road—bringing businesses and customers together in one of Kathmandu’s most important marketplaces.": "बदलिँदा प्रवृत्ति र व्यवसायका पुस्तासँगै, यो कम्प्लेक्स न्यू रोडको रौनकसँग जोडिरह्यो र काठमाडौंको प्रमुख बजारमध्ये एकमा व्यवसाय तथा ग्राहकलाई नजिक ल्याइरह्यो।",
  "RB Complex — A legacy of business in the heart of Kathmandu.": "आर.बी. कम्प्लेक्स — काठमाडौंको मुटुमा व्यवसायको विरासत।",
  "This searchable directory is ready to be populated with the actual R.B. Complex tenant list.": "यो खोज्न मिल्ने निर्देशिका आर.बी. कम्प्लेक्सका वास्तविक पसलहरूको सूची थप्न तयार छ।",
  "6 sample stores found": "६ वटा नमुना पसल भेटिए",
  "Demo shop names/unit numbers only — replace with verified tenant data for production.": "यहाँ देखाइएका पसलको नाम र युनिट नम्बर नमुना मात्र हुन्। प्रत्यक्ष वेबसाइटमा प्रमाणित विवरण राखिनेछ।",
  "Long store pages help visitors understand the retail mix before they search individual names.": "विस्तृत पसल पृष्ठले आगन्तुकलाई व्यक्तिगत नाम खोज्नुअघि यहाँका पसलहरूको विविधता बुझ्न मद्दत गर्छ।",
  "Ground floor": "भुइँतल्ला",
  "First floor": "पहिलो तल्ला",
  "Second floor": "दोस्रो तल्ला",
  "Third floor": "तेस्रो तल्ला",
  "Each floor can have its own mini-directory, key categories and highlights.": "हरेक तल्लामा छुट्टै सानो निर्देशिका, मुख्य श्रेणी र विशेष आकर्षण राख्न सकिन्छ।",
  "Entry-level retail, fashion and everyday shopping.": "प्रवेशतल्लाका खुद्रा पसल, फेसन र दैनिक किनमेल।",
  "Fashion, footwear and related retail categories.": "फेसन, जुत्ता र सम्बन्धित खुद्रा श्रेणीहरू।",
  "Mobile, electronics, accessories and specialist retail.": "मोबाइल, इलेक्ट्रोनिक्स, एक्सेसरिज र विशेष खुद्रा पसलहरू।",
  "Services, specialty businesses and additional retail.": "सेवा, विशेष व्यवसाय र थप खुद्रा पसलहरू।",
  "Use visual category discovery for people who know what they want, but not the exact store name.": "पसलको सही नाम थाहा नभए पनि आवश्यक वस्तु खोज्न दृश्यात्मक श्रेणी प्रयोग गर्नुहोस्।",
  "Clothing & style": "पोशाक र शैली",
  "Browse category": "श्रेणी हेर्नुहोस्",
  "Shoes & more": "जुत्ता र थप",
  "Finishing touches": "अन्तिम स्पर्श",
  "Tech & services": "प्रविधि र सेवाहरू",
  "A production directory can add favourite stores, click-to-call, map locations and accessible routes.": "प्रत्यक्ष निर्देशिकामा मनपरेका पसल, क्लिक गरेर फोन गर्ने सुविधा, नक्सा र पहुँचयोग्य मार्ग थप्न सकिन्छ।",
  "Search": "खोज्नुहोस्",
  "Find a tenant instantly by name or category.": "नाम वा श्रेणीबाट तुरुन्त पसल खोज्नुहोस्।",
  "Locate": "स्थान पत्ता लगाउनुहोस्",
  "Jump from a store listing to its floor position.": "पसल सूचीबाट सिधै सम्बन्धित तल्लाको स्थानमा जानुहोस्।",
  "Contact": "सम्पर्क",
  "Add verified store numbers and direct contact actions.": "प्रमाणित पसल नम्बर र सिधा सम्पर्क सुविधा थप्नुहोस्।",
  "Save": "सेभ गर्नुहोस्",
  "Future option for visitors to save stores before arriving.": "आगमनअघि मनपरेका पसल सेभ गर्ने सुविधा भविष्यमा थप्न सकिन्छ।",
  "Move directly from store discovery to practical visitor information.": "पसल खोजेपछि सिधै उपयोगी आगन्तुक जानकारीमा जानुहोस्।",
  "Plan a visit ↗": "भ्रमण योजना बनाउनुहोस् ↗",
  "These are presentation examples, not actual R.B. Complex promotions.": "यी प्रस्तुतीकरणका उदाहरण मात्र हुन्, आर.बी. कम्प्लेक्सका वास्तविक प्रचार होइनन्।",
  "Fashion week": "फेसन सप्ताह",
  "Up to 30% off*": "३०% सम्म छुट*",
  "Prototype campaign for participating fashion stores.": "सहभागी फेसन पसलका लागि नमुना अभियान।",
  "Weekend edit": "सप्ताहन्त विशेष",
  "Feature store-led offers in this space.": "यस स्थानमा पसलका विशेष अफर देखाउनुहोस्।",
  "Tech deals": "प्रविधि अफरहरू",
  "Highlight selected device and accessory promotions.": "छनोट गरिएका उपकरण र एक्सेसरिजका प्रचारहरू देखाउनुहोस्।",
  "*Prototype promotional copy only.": "*यो प्रचार सामग्रीको नमुना मात्र हो।",
  "Refresh your wardrobe.": "आफ्नो पहिरन नयाँ बनाउनुहोस्।",
  "Step into the weekend.": "सप्ताहन्तका लागि तयार हुनुहोस्।",
  "Small details. Big difference.": "साना विवरण, ठूलो फरक।",
  "Upgrade your everyday.": "दैनिक जीवनलाई अझ सहज बनाउनुहोस्।",
  "New offers should make the website feel": "नयाँ अफरले वेबसाइटलाई",
  "different every week.": "हरेक हप्ता नयाँ अनुभूति दिनुपर्छ।",
  "Participating stores": "सहभागी पसलहरू",
  "Dates & conditions": "मिति र सर्तहरू",
  "See what's on →": "के हुँदैछ हेर्नुहोस् →",
  "A real mall website needs fresh content. This page can later be managed as an events/news section.": "एउटा सक्रिय मल वेबसाइटका लागि नयाँ सामग्री आवश्यक हुन्छ। यस पृष्ठलाई पछि कार्यक्रम र समाचार खण्डका रूपमा व्यवस्थापन गर्न सकिन्छ।",
  "Prototype event": "नमुना कार्यक्रम",
  "New Season Edit": "नयाँ मौसम विशेष",
  "A curated fashion-focused campaign across participating stores.": "सहभागी पसलहरूमा केन्द्रित फेसन अभियान।",
  "New opening": "नयाँ उद्घाटन",
  "Something new is coming": "केही नयाँ आउँदैछ",
  "Use this card to announce a new tenant or refreshed space.": "नयाँ पसल वा नयाँ स्वरूप पाएको स्थानको जानकारी दिन यो कार्ड प्रयोग गर्नुहोस्।",
  "Meet. Shop. Stay.": "भेटघाट। किनमेल। रमाइलो।",
  "Promote weekend activations or seasonal visitor experiences.": "सप्ताहन्तका गतिविधि वा मौसमी आगन्तुक अनुभवको प्रचार गर्नुहोस्।",
  "Mon": "सोम",
  "Tue": "मंगल",
  "Wed": "बुध",
  "Thu": "बिही",
  "Fri": "शुक्र",
  "Sat": "शनि",
  "New arrivals": "नयाँ आगमन",
  "Store spotlight": "विशेष पसल",
  "Style edit": "शैली विशेष",
  "Weekend offers": "सप्ताहन्त अफरहरू",
  "Visitor moment": "आगन्तुक विशेष",
  "A new space joins R.B. Complex": "आर.बी. कम्प्लेक्समा नयाँ स्थान थपियो",
  "Seasonal edit": "मौसमी विशेष",
  "Make a day of New Road": "न्यू रोडमा दिनभरि रमाउनुहोस्",
  "Plan your visit →": "भ्रमण योजना बनाउनुहोस् →",
  "A visual collection of fresh finds, everyday style and moments from the R.B. Complex experience.": "आर.बी. कम्प्लेक्सका नयाँ रोजाइ, दैनिक शैली र अनुभवका झलकहरूको दृश्य संग्रह।",
  "From fashion and footwear to technology and everyday essentials, explore the spirit of the complex through the collection below.": "फेसन र जुत्तादेखि प्रविधि तथा दैनिक आवश्यकतासम्म, तलको संग्रहबाट कम्प्लेक्सको रौनक अनुभव गर्नुहोस्।",
  "A bright, contemporary retail moment.": "उज्यालो र आधुनिक किनमेल अनुभव।",
  "Fashion finds for every day.": "हरेक दिनका लागि फेसन रोजाइ।",
  "Footwear and fresh arrivals.": "जुत्ता र नयाँ आगमन।",
  "Meet, browse and enjoy New Road.": "भेटघाट गर्नुहोस्, पसल हेर्नुहोस् र न्यू रोडको रौनक लिनुहोस्।",
  "Devices and accessories to discover.": "खोज्न लायक उपकरण र एक्सेसरिज।",
  "Beauty and personal style.": "सौन्दर्य र व्यक्तिगत शैली।",
  "Retail in motion": "चलायमान किनमेल",
  "A changing collection of new finds.": "नयाँ रोजाइको बदलिँदो संग्रह।",
  "Accessories for the everyday.": "दैनिक प्रयोगका एक्सेसरिज।",
  "Articles share shopping inspiration and practical ideas for your next day in Kathmandu’s New Road district.": "काठमाडौंको न्यू रोडमा तपाईंको अर्को दिनका लागि किनमेल प्रेरणा र उपयोगी सुझावहरू।",
  "Style guide": "शैली मार्गदर्शिका",
  "A fresh way to shop New Road": "न्यू रोडमा किनमेल गर्ने नयाँ तरिका",
  "From everyday essentials to a statement piece, build a shopping list that leaves space for an unexpected find.": "दैनिक आवश्यकतादेखि विशेष रोजाइसम्म, अप्रत्याशित मनपर्ने सामानका लागि ठाउँ छोडेर किनमेल सूची बनाउनुहोस्।",
  "Step into the new season": "नयाँ मौसममा पाइला चाल्नुहोस्",
  "Footwear is where comfort and personal style meet. Explore the shapes and finishes worth watching this season.": "जुत्तामा आराम र व्यक्तिगत शैलीको भेट हुन्छ। यस मौसमका ध्यान दिनलायक डिजाइन र फिनिस हेर्नुहोस्।",
  "Technology": "प्रविधि",
  "The everyday tech edit": "दैनिक प्रविधिका रोजाइ",
  "A short guide to finding useful devices, accessories and upgrades while you are in the city.": "सहरमा रहँदा उपयोगी उपकरण, एक्सेसरिज र अपग्रेड खोज्नका लागि छोटो मार्गदर्शिका।",
  "The details that complete a look": "शैली पूरा गर्ने विवरणहरू",
  "Watches, wallets and finishing touches make thoughtful gifts and effortless everyday additions.": "घडी, वालेट र साना एक्सेसरिज विचारपूर्ण उपहार तथा दैनिक शैलीका सहज रोजाइ हुन्।",
  "Beauty": "सौन्दर्य",
  "A little time for yourself": "आफ्नो लागि केही समय",
  "Discover personal care and beauty essentials that bring a small lift to your regular routine.": "दैनिक दिनचर्यामा ताजगी थप्ने व्यक्तिगत हेरचाह र सौन्दर्यका आवश्यक वस्तु खोज्नुहोस्।",
  "Visit guide": "भ्रमण मार्गदर्शिका",
  "Plan the stores you want to visit, leave time to explore, and enjoy the neighbourhood along the way.": "जान चाहेका पसलको योजना बनाउनुहोस्, घुम्न समय छुट्याउनुहोस् र बाटोमै न्यू रोडको माहोल अनुभव गर्नुहोस्।",
  "Opening hours and amenity details should be verified with management before publication.": "खुल्ने समय र सुविधासम्बन्धी विवरण प्रकाशनअघि व्यवस्थापनबाट पुष्टि गरिनुपर्छ।",
  "Use this page for directions, official hours, parking guidance and visitor services.": "दिशानिर्देश, आधिकारिक समय, पार्किङ जानकारी र आगन्तुक सेवाका लागि यो पृष्ठ प्रयोग गर्नुहोस्।",
  "New Road (Pukhudhyan Marg / Ranamukteshwor Marg), Kathmandu, Nepal": "न्यू रोड (पुखुद्याँ मार्ग / राणामुक्तेश्वर मार्ग), काठमाडौं, नेपाल",
  "Individual store schedules and holiday availability may vary.": "हरेक पसलको समय र बिदाको उपलब्धता फरक हुन सक्छ।",
  "Area reserved for verified visitor parking information.": "प्रमाणित आगन्तुक पार्किङ जानकारीका लागि छुट्याइएको स्थान।",
  "Area for lift, stairs and accessibility details.": "लिफ्ट, सिँढी र पहुँचसम्बन्धी जानकारीका लागि स्थान।",
  "Area for ATMs, help points and useful facilities.": "एटिएम, सहायता कक्ष र उपयोगी सुविधासम्बन्धी जानकारीका लागि स्थान।",
  "Important notices and guidance can be displayed here.": "महत्वपूर्ण सूचना र मार्गदर्शन यहाँ देखाउन सकिन्छ।",
  "Search stores": "पसलहरू खोज्नुहोस्",
  "Know the shops and floors you want to visit.": "जान चाहेका पसल र तल्लाबारे पहिले नै जानकारी लिनुहोस्।",
  "Find New Road": "न्यू रोड खोज्नुहोस्",
  "Open directions and note current visitor guidance.": "दिशानिर्देश खोल्नुहोस् र हालको आगन्तुक जानकारी हेर्नुहोस्।",
  "Use the directory": "निर्देशिका प्रयोग गर्नुहोस्",
  "Find the floor, shop number and useful amenities.": "तल्ला, पसल नम्बर र उपयोगी सुविधा खोज्नुहोस्।",
  "See what's next": "अब के छ हेर्नुहोस्",
  "Check new offers or plan another visit.": "नयाँ अफर हेर्नुहोस् वा अर्को भ्रमणको योजना बनाउनुहोस्।",
  "Do all stores follow the same schedule?": "के सबै पसलको समय एउटै हुन्छ?",
  "Where can visitors park?": "आगन्तुकले कहाँ पार्किङ गर्न सक्छन्?",
  "How do I find a particular store?": "कुनै विशेष पसल कसरी खोज्ने?",
  "How can I contact R.B. Complex?": "आर.बी. कम्प्लेक्ससँग कसरी सम्पर्क गर्ने?",
  "Open directions or check your stores one more time before leaving.": "निस्कनुअघि दिशानिर्देश खोल्नुहोस् वा आफ्नो पसल सूची फेरि हेर्नुहोस्।",
  "A clean commercial proposition for retailers, service businesses and brands considering space at R.B. Complex.": "आर.बी. कम्प्लेक्समा स्थान खोजिरहेका खुद्रा विक्रेता, सेवा व्यवसाय र ब्रान्डका लागि स्पष्ट व्यावसायिक प्रस्ताव।",
  "This demo form works visually but does not transmit data.": "यो नमुना फारम दृश्यात्मक रूपमा मात्र काम गर्छ; यसले जानकारी पठाउँदैन।",
  "Demo complete. Your enquiry has not been sent. Please contact mall management directly.": "नमुना प्रक्रिया पूरा भयो। तपाईंको सोधपुछ पठाइएको छैन। कृपया मल व्यवस्थापनसँग सिधै सम्पर्क गर्नुहोस्।",
  "This section gives prospective tenants the context they expect before filling in a leasing form.": "यो खण्डले सम्भावित भाडेदारलाई लिजिङ फारम भर्नुअघि आवश्यक पृष्ठभूमि जानकारी दिन्छ।",
  "Central commercial area": "केन्द्रीय व्यावसायिक क्षेत्र",
  "Multi-category retail mix": "विविध श्रेणीका पसलहरू",
  "Multiple floor opportunities": "विभिन्न तल्लामा अवसर",
  "Direct management enquiry": "व्यवस्थापनसँग सिधा सोधपुछ",
  "A strong leasing page should visually show available units instead of asking businesses to call blindly. The units below are prototype placeholders.": "प्रभावकारी लिजिङ पृष्ठले व्यवसायलाई अनिश्चित रूपमा फोन गर्न लगाउनुको सट्टा उपलब्ध युनिट स्पष्ट देखाउनुपर्छ। तलका युनिट नमुना मात्र हुन्।",
  "Concept vacancy": "नमुना खाली स्थान",
  "Put your brand in view.": "आफ्नो ब्रान्डलाई देखिने ठाउँमा राख्नुहोस्।",
  "Ground-floor unit": "भुइँतल्लाको युनिट",
  "High-visibility prototype space.": "धेरै देखिने नमुना स्थान।",
  "Enquire": "सोधपुछ गर्नुहोस्",
  "First-floor unit": "पहिलो तल्लाको युनिट",
  "Fashion / footwear prototype positioning.": "फेसन / जुत्ता पसलका लागि नमुना स्थान।",
  "Second-floor unit": "दोस्रो तल्लाको युनिट",
  "Electronics / accessory prototype positioning.": "इलेक्ट्रोनिक्स / एक्सेसरिज पसलका लागि नमुना स्थान।",
  "Third-floor unit": "तेस्रो तल्लाको युनिट",
  "Service / specialty prototype positioning.": "सेवा / विशेष पसलका लागि नमुना स्थान।",
  "A clear process helps a prospective tenant understand what happens after an enquiry.": "स्पष्ट प्रक्रियाले सोधपुछपछि के हुन्छ भन्ने सम्भावित भाडेदारलाई बुझ्न मद्दत गर्छ।",
  "Share your business, category, preferred floor and space requirements.": "आफ्नो व्यवसाय, श्रेणी, चाहिएको तल्ला र स्थानको आवश्यकता बताउनुहोस्।",
  "Discuss": "छलफल",
  "Management reviews availability and commercial fit.": "व्यवस्थापनले उपलब्धता र व्यावसायिक उपयुक्तता समीक्षा गर्छ।",
  "Inspect suitable spaces and understand the location in person.": "उपयुक्त स्थान निरीक्षण गर्नुहोस् र स्थलमै गएर बुझ्नुहोस्।",
  "Agree": "सहमति",
  "Move into formal commercial terms and fit-out planning.": "औपचारिक व्यावसायिक सर्त र सजावट योजनातर्फ अघि बढ्नुहोस्।",
  "What kinds of businesses can apply?": "कस्ता व्यवसायले आवेदन दिन सक्छन्?",
  "Are unit sizes and rents shown online?": "के युनिटको आकार र भाडा अनलाइन देखाइन्छ?",
  "Can I arrange a site visit?": "के म स्थल अवलोकनको समय मिलाउन सक्छु?",
  "Imagine your storefront here": "आफ्नो पसलको अगाडिको दृश्य यहाँ कल्पना गर्नुहोस्",
  "Start with a conversation.": "कुराकानीबाट सुरु गर्नुहोस्।",
  "Build from there.": "त्यहीँबाट अगाडि बढ्नुहोस्।",
  "“The digital version of R.B. should feel as active as": "“आर.बी. कम्प्लेक्सको डिजिटल रूप पनि",
  "New Road itself.": "न्यू रोडजत्तिकै जीवन्त महसुस हुनुपर्छ।",
  "Long offer pages work best when campaigns are grouped by category and have clear expiry / participation details.": "अभियानलाई श्रेणीअनुसार समूहबद्ध गरी समाप्ति मिति र सहभागिताको स्पष्ट विवरण राख्दा अफर पृष्ठ अझ उपयोगी हुन्छ।",
  "Prototype campaign card for fashion tenants.": "फेसन पसलका लागि नमुना अभियान कार्ड।",
  "Feature store-specific footwear offers here.": "यहाँ पसल-विशेष जुत्ताका अफर देखाउनुहोस्।",
  "Use this space for accessory and beauty promotions.": "यो स्थान एक्सेसरिज र सौन्दर्यसम्बन्धी प्रचारका लागि प्रयोग गर्नुहोस्।",
  "Device, accessory and service offer campaigns.": "उपकरण, एक्सेसरिज र सेवासम्बन्धी अफर अभियान।",
  "Every real promotion should show participating stores, expiry dates and conditions. These examples are purely design placeholders.": "हरेक वास्तविक प्रचारमा सहभागी पसल, समाप्ति मिति र सर्त स्पष्ट हुनुपर्छ। यी उदाहरण डिजाइनका लागि मात्र हुन्।",
  "Each live offer can list the exact stores taking part, with links back to the directory.": "हरेक सक्रिय अफरमा सहभागी पसलको स्पष्ट सूची र निर्देशिकातर्फको लिङ्क राख्न सकिन्छ।",
  "Add campaign validity dates and concise terms to prevent ambiguity for visitors.": "आगन्तुकलाई अन्योल नहोस् भनेर अभियानको वैध मिति र छोटा सर्त राख्नुहोस्।",
  "Connect promotions with events and new openings to keep visitors returning.": "आगन्तुकलाई फेरि आउन प्रेरित गर्न प्रचारलाई कार्यक्रम र नयाँ उद्घाटनसँग जोड्नुहोस्।",
  "A compact event calendar makes a mall site feel actively managed rather than static.": "संक्षिप्त कार्यक्रम क्यालेन्डरले मल वेबसाइटलाई स्थिर होइन, सक्रिय रूपमा व्यवस्थापन गरिएको अनुभूति दिन्छ।",
  "Use editorial content for store openings, campaigns, tenant stories and announcements.": "पसल उद्घाटन, अभियान, पसलका कथा र घोषणाका लागि सम्पादकीय सामग्री प्रयोग गर्नुहोस्।",
  "Social-style imagery and a newsletter can create a reason for people to revisit the site even when they are not actively searching for a store.": "सामाजिक सञ्जालजस्तो दृश्य सामग्री र समाचारपत्रले पसल नखोजिरहेकै बेला पनि आगन्तुकलाई वेबसाइटमा फेरि आउन प्रेरित गर्न सक्छ।",
  "Events work best when the next action is simple: get directions and visit.": "अर्को कदम सरल हुँदा कार्यक्रम अझ प्रभावकारी हुन्छ: दिशानिर्देश लिनुहोस् र भ्रमण गर्नुहोस्।",
  "Transport guidance should eventually be verified and tailored to New Road traffic, parking and pedestrian access.": "यातायातसम्बन्धी जानकारी अन्ततः न्यू रोडको ट्राफिक, पार्किङ र पैदल पहुँचअनुसार पुष्टि र अनुकूल बनाउनुपर्छ।",
  "Clear landmark-based directions can help visitors already in the New Road area.": "स्पष्ट स्थलचिन्हमा आधारित दिशानिर्देशले न्यू रोड क्षेत्रमा रहेका आगन्तुकलाई मद्दत गर्छ।",
  "Add verified approach routes, parking guidance and busy-hour notices.": "प्रमाणित पहुँच मार्ग, पार्किङ जानकारी र व्यस्त समयका सूचना थप्नुहोस्।",
  "Future content can highlight practical drop-off points and nearby transit access.": "भविष्यको सामग्रीमा उपयोगी झर्ने स्थान र नजिकका सार्वजनिक यातायात पहुँचबारे जानकारी दिन सकिन्छ।",
  "A useful visit page combines planning, amenities, directions and store discovery in one long, easy-to-scan experience.": "उपयोगी भ्रमण पृष्ठले योजना, सुविधा, दिशानिर्देश र पसल खोज्ने जानकारीलाई एउटै सहज रूपमा पढ्न मिल्ने अनुभवमा जोड्छ।",
  "These are prototype FAQ topics. Official answers should come from R.B. Complex management.": "यी नमुना सोधिने प्रश्न हुन्। आधिकारिक उत्तर आर.बी. कम्प्लेक्स व्यवस्थापनबाट आउनुपर्छ।",
  "Individual store schedules and festival availability may vary. Contact a store directly when planning a specific visit.": "हरेक पसलको समय र चाडपर्वको उपलब्धता फरक हुन सक्छ। विशेष भ्रमणको योजना बनाउँदा सम्बन्धित पसलसँग सिधै सम्पर्क गर्नुहोस्।",
  "The site should publish only verified parking locations, capacity information and any applicable visitor rules.": "वेबसाइटमा प्रमाणित पार्किङ स्थान, क्षमता विवरण र लागू हुने आगन्तुक नियम मात्र प्रकाशित हुनुपर्छ।",
  "Use the searchable Stores page. A production version can connect each tenant to a verified floor position and unit number.": "खोज्न मिल्ने पसल पृष्ठ प्रयोग गर्नुहोस्। प्रत्यक्ष संस्करणमा हरेक पसललाई प्रमाणित तल्ला स्थान र युनिट नम्बरमा जोड्न सकिन्छ।",
  "The prototype currently shows the public directory number 01-4220503. Official contact channels should be confirmed before launch.": "नमुनामा हाल सार्वजनिक निर्देशिका नम्बर ०१–४२२०५०३ देखाइएको छ। सार्वजनिक गर्नुअघि आधिकारिक सम्पर्क माध्यम पुष्टि हुनुपर्छ।",
  "Actual commercial terms should never be invented on the public site. Management can decide which details to publish.": "सार्वजनिक वेबसाइटमा वास्तविक व्यावसायिक सर्त अनुमान गरेर राख्नु हुँदैन। कुन विवरण प्रकाशन गर्ने भन्ने व्यवस्थापनले तय गर्न सक्छ।",
  "The production site can list preferred or permitted categories once management confirms its leasing policy.": "व्यवस्थापनले लिजिङ नीति पुष्टि गरेपछि प्रत्यक्ष वेबसाइटमा प्राथमिक वा अनुमति प्राप्त श्रेणीहरू राख्न सकिन्छ।",
  "They can be, if management wants them public. Otherwise the website can display availability and request contact details for commercial information.": "व्यवस्थापनले सार्वजनिक गर्न चाहेमा देखाउन सकिन्छ। अन्यथा वेबसाइटमा उपलब्धता देखाएर व्यावसायिक जानकारीका लागि सम्पर्क विवरण माग्न सकिन्छ।",
  "A production enquiry form can include a preferred date and route the request directly to the leasing team.": "प्रत्यक्ष सोधपुछ फारममा रुचाइएको मिति राखी अनुरोधलाई सिधै लिजिङ टोलीसम्म पठाउन सकिन्छ।",
  "The final leasing journey should feel professional enough for established brands and simple enough for independent businesses.": "अन्तिम लिजिङ प्रक्रिया स्थापित ब्रान्डका लागि व्यावसायिक र स्वतन्त्र व्यवसायका लागि सहज हुनुपर्छ।",
};

function getCache(): Cache {
  try {
    return JSON.parse(window.localStorage.getItem(storageKey) || "{}");
  } catch {
    return {};
  }
}

async function translate(text: string, cache: Cache) {
  if (preferredTranslations[text]) return preferredTranslations[text].replaceAll("हरू", "हरु");
  return text;
}

export default function GoogleTranslate() {
  const pathname = usePathname();

  useEffect(() => {
    if (window.localStorage.getItem("rb-language") !== "ne") return;
    document.documentElement.lang = "ne";
    const normalizePluralSuffix = () => {
      const spellingWalker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
      let spellingNode: Node | null;
      while ((spellingNode = spellingWalker.nextNode())) {
        if (spellingNode.textContent?.includes("हरू")) {
          spellingNode.textContent = spellingNode.textContent.replaceAll("हरू", "हरु");
        }
      }
    };
    normalizePluralSuffix();
    const spellingObserver = new MutationObserver(normalizePluralSuffix);
    spellingObserver.observe(document.body, { childList: true, characterData: true, subtree: true });
    const cache = getCache();
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const nodes: Text[] = [];
    let node: Node | null;
    while ((node = walker.nextNode())) {
      const text = node.textContent?.trim() || "";
      const parent = node.parentElement;
      if (
        text.length > 1 &&
        /[A-Za-z]/.test(text) &&
        parent &&
        !parent.closest("script, style, svg, .language-switcher, .brand, .header, .mall-footer")
      ) nodes.push(node as Text);
    }
    const attributes = [...document.querySelectorAll<HTMLElement>("[placeholder], [aria-label]")]
      .flatMap((element) => (["placeholder", "aria-label"] as const)
        .map((attribute) => ({ element, attribute, value: element.getAttribute(attribute) || "" })))
      .filter(({ value }) => value.length > 1 && /[A-Za-z]/.test(value));

    let cancelled = false;
    const queue = [...nodes];
    async function worker() {
      while (!cancelled && queue.length) {
        const textNode = queue.shift();
        if (!textNode) return;
        const original = textNode.textContent || "";
        const match = original.match(/^(\s*)([\s\S]*?)(\s*)$/);
        if (!match || !match[2]) continue;
        try {
          const translated = await translate(match[2], cache);
          if (!cancelled) textNode.textContent = `${match[1]}${translated}${match[3]}`;
        } catch {
          // Keep the original English text if a translation request is unavailable.
        }
      }
    }
    void Promise.all(Array.from({ length: 16 }, worker)).then(() => {
      const attributeQueue = [...attributes];
      async function attributeWorker() {
        while (!cancelled && attributeQueue.length) {
          const item = attributeQueue.shift();
          if (!item) return;
          try {
            const translated = await translate(item.value, cache);
            if (!cancelled) item.element.setAttribute(item.attribute, translated);
          } catch {
            // Keep the original attribute if a translation request is unavailable.
          }
        }
      }
      void Promise.all(Array.from({ length: 8 }, attributeWorker)).then(() => {
        try { window.localStorage.setItem(storageKey, JSON.stringify(cache)); } catch {}
      });
    });
    return () => { cancelled = true; spellingObserver.disconnect(); };
  }, [pathname]);

  return null;
}
