import Link from "next/link";
const posts: Record<string, { title: string; category: string; image: string; excerpt: string; body: string[] }> = {
  "fresh-way-to-shop-new-road": { title: "A fresh way to shop New Road", category: "Style guide", image: "/images/product-fashion.png", excerpt: "Build a shopping list that leaves room for an unexpected find.", body: ["New Road rewards a little curiosity. Start with the pieces you need, then let the shops and displays add something unexpected to your list.", "Choose one anchor item first: a shirt, bag or pair of shoes you know you will wear often. Use that as the starting point for colours, textures and accessories."] },
  "step-into-the-new-season": { title: "Step into the new season", category: "New arrivals", image: "/images/product-footwear.png", excerpt: "Footwear is where comfort and personal style meet.", body: ["The right pair of shoes can change the way an entire outfit feels. Look for a shape that works with the clothes you already reach for most often.", "Try shoes on with the kind of socks you wear day to day, and take a few steps before deciding."] },
  "everyday-tech-edit": { title: "The everyday tech edit", category: "Technology", image: "/images/product-electronics.png", excerpt: "Useful devices and accessories for everyday life.", body: ["The most useful technology fits quietly into your routine. Think about commuting, listening, charging and staying organised.", "Prioritise battery life, comfort and compatibility before choosing an accessory."] },
  "details-that-complete-a-look": { title: "The details that complete a look", category: "Accessories", image: "/images/product-accessories.png", excerpt: "Watches, wallets and finishing touches make thoughtful gifts and effortless everyday additions.", body: ["Accessories are often the most personal part of a look. A well-made wallet or watch can become something you use every day.", "Choose materials and finishes that suit an everyday routine, then let the small details make the outfit feel complete."] },
  "a-little-time-for-yourself": { title: "A little time for yourself", category: "Beauty", image: "/images/product-beauty.png", excerpt: "Discover personal care and beauty essentials that bring a small lift to your regular routine.", body: ["A personal-care routine does not need to be complicated. A few well-chosen essentials can create a calm moment at the beginning or end of the day.", "Start with products you know you will use consistently, then add something new when it feels useful."] },
  "make-a-day-of-new-road": { title: "Make a day of New Road", category: "Visit guide", image: "/images/shopping-4.jpg", excerpt: "Plan the stores you want to visit, leave time to explore, and enjoy the neighbourhood along the way.", body: ["A relaxed New Road visit starts with a simple plan. Make note of the stores you want to see, then leave time for a coffee and a few unplanned stops.", "R.B. Complex is part of a lively neighbourhood. Treat the visit as a chance to discover something beyond the first thing you came for."] },
};
export function generateStaticParams() { return Object.keys(posts).map(slug => ({ slug })); }
export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const post = posts[slug] ?? posts["fresh-way-to-shop-new-road"]; return <div className="view active"><article className="story-page"><header><div><p className="eyebrow">{post.category}</p><h1>{post.title}</h1><p>{post.excerpt}</p><Link href="/blog/">← Back to stories</Link></div><img src={post.image} alt="" /></header><div className="story-body">{post.body.map(p => <p key={p}>{p}</p>)}<Link className="btn btn-dark" href="/stores/">Explore stores</Link></div></article></div>; }
